//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietKePhanMem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENBANTHI
    {
        public string maBB { get; set; }
        public string sbd { get; set; }
        public System.DateTime ngaylap { get; set; }
    
        public virtual THISINH THISINH { get; set; }
    }
}
