//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietKePhanMem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANBOCOITHI
    {
        public CANBOCOITHI()
        {
            this.LICHTHIs = new HashSet<LICHTHI>();
        }
    
        public string maCB { get; set; }
        public string tenCB { get; set; }
        public string donvi { get; set; }
        public string chucvu { get; set; }
    
        public virtual ICollection<LICHTHI> LICHTHIs { get; set; }
    }
}
