//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietKePhanMem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTHI
    {
        public string maCB { get; set; }
        public string maMH { get; set; }
        public string malop { get; set; }
        public Nullable<System.DateTime> ngaythi { get; set; }
        public string phongthi { get; set; }
    
        public virtual CANBOCOITHI CANBOCOITHI { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MONTHI MONTHI { get; set; }
    }
}
