//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietKePhanMem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class thivachamthiEntities5 : DbContext
    {
        public thivachamthiEntities5()
            : base("name=thivachamthiEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAITHI> BAITHIs { get; set; }
        public DbSet<BIENBANTHI> BIENBANTHIs { get; set; }
        public DbSet<CANBOCOITHI> CANBOCOITHIs { get; set; }
        public DbSet<DETHIVADAPAN> DETHIVADAPANs { get; set; }
        public DbSet<GIAOVIENCHAMTHI> GIAOVIENCHAMTHIs { get; set; }
        public DbSet<LICHTHI> LICHTHIs { get; set; }
        public DbSet<LOP> LOPs { get; set; }
        public DbSet<MONTHI> MONTHIs { get; set; }
        public DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<THISINH> THISINHs { get; set; }
    
        [EdmFunction("thivachamthiEntities5", "THONGKEBAITHI")]
        public virtual IQueryable<THONGKEBAITHI_Result> THONGKEBAITHI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<THONGKEBAITHI_Result>("[thivachamthiEntities5].[THONGKEBAITHI]()");
        }
    
        [EdmFunction("thivachamthiEntities5", "THONGKEBIENBANVIPHAM")]
        public virtual IQueryable<THONGKEBIENBANVIPHAM_Result> THONGKEBIENBANVIPHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<THONGKEBIENBANVIPHAM_Result>("[thivachamthiEntities5].[THONGKEBIENBANVIPHAM]()");
        }
    
        [EdmFunction("thivachamthiEntities5", "THONGKEDIEMTHITHEOLOP")]
        public virtual IQueryable<THONGKEDIEMTHITHEOLOP_Result> THONGKEDIEMTHITHEOLOP(string lOP, string mONTHI)
        {
            var lOPParameter = lOP != null ?
                new ObjectParameter("LOP", lOP) :
                new ObjectParameter("LOP", typeof(string));
    
            var mONTHIParameter = mONTHI != null ?
                new ObjectParameter("MONTHI", mONTHI) :
                new ObjectParameter("MONTHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<THONGKEDIEMTHITHEOLOP_Result>("[thivachamthiEntities5].[THONGKEDIEMTHITHEOLOP](@LOP, @MONTHI)", lOPParameter, mONTHIParameter);
        }
    
        [EdmFunction("thivachamthiEntities5", "THONGKELICHTHI")]
        public virtual IQueryable<THONGKELICHTHI_Result> THONGKELICHTHI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<THONGKELICHTHI_Result>("[thivachamthiEntities5].[THONGKELICHTHI]()");
        }
    
        [EdmFunction("thivachamthiEntities5", "THONGKETHEOCANBO")]
        public virtual IQueryable<THONGKETHEOCANBO_Result> THONGKETHEOCANBO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<THONGKETHEOCANBO_Result>("[thivachamthiEntities5].[THONGKETHEOCANBO]()");
        }
    }
}
