//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietKePhanMem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTHI
    {
        public MONTHI()
        {
            this.BAITHIs = new HashSet<BAITHI>();
            this.DETHIVADAPANs = new HashSet<DETHIVADAPAN>();
            this.GIAOVIENCHAMTHIs = new HashSet<GIAOVIENCHAMTHI>();
            this.LICHTHIs = new HashSet<LICHTHI>();
        }
    
        public string maMH { get; set; }
        public string tenMH { get; set; }
        public int soDVHT { get; set; }
        public string hinhthucthi { get; set; }
    
        public virtual ICollection<BAITHI> BAITHIs { get; set; }
        public virtual ICollection<DETHIVADAPAN> DETHIVADAPANs { get; set; }
        public virtual ICollection<GIAOVIENCHAMTHI> GIAOVIENCHAMTHIs { get; set; }
        public virtual ICollection<LICHTHI> LICHTHIs { get; set; }
    }
}
