//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietKePhanMem
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public string tendangnhap { get; set; }
        public string matkhau { get; set; }
        public string tennguoidung { get; set; }
        public int loaitaikhoan { get; set; }
    }
}
