//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietKePhanMem
{
    using System;
    using System.Collections.Generic;
    
    public partial class THISINH
    {
        public THISINH()
        {
            this.BAITHIs = new HashSet<BAITHI>();
            this.BIENBANTHIs = new HashSet<BIENBANTHI>();
        }
    
        public string sbd { get; set; }
        public string hoten { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public string malop { get; set; }
    
        public virtual ICollection<BAITHI> BAITHIs { get; set; }
        public virtual ICollection<BIENBANTHI> BIENBANTHIs { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
